name: Build and Push NSE Image

on:
  push:
    branches:
      - main
    paths:
      - "ingest/**"

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  REGION: asia-south1
  REPOSITORY: nse
  IMAGE_NAME: nse-ingestion
  CLOUD_RUN_JOB: nse-ingestion-job

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Authenticate GitHub -> Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.TERRAFORM_SERVICE_ACCOUNT }}

      # 3. Setup gcloud
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # 4. Configure Docker authentication
      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

      # 5. Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA} \
            ./ingest

      # 6. Push Docker image
      - name: Push Docker image
        run: |
          docker push \
            ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA}

      # 7. Update Cloud Run Job with new image
      - name: Update Cloud Run Job
        run: |
          gcloud run jobs update ${CLOUD_RUN_JOB} \
            --image=${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA} \
            --region=${REGION} \
            --project=${PROJECT_ID}

      # 8. Execute Cloud Run Job
      - name: Execute Cloud Run Job
        run: |
          gcloud run jobs execute ${CLOUD_RUN_JOB} \
            --region=${REGION} \
            --project=${PROJECT_ID} \
            --wait
